### ISSUE TITLE
Appeditor Installed from flatpak on flathub cannot see my menu entries #50

### ISSUE THREAD

**Issue by stuaxo** [flathub/com.github.donadigo.appeditor#6]
This bug is from  https://github.com/donadigo/appeditor/issues/50#issuecomment-384021409

I guess there is some sandboxing that stops it editing my menus ?

![image](https://user-images.githubusercontent.com/179677/39127774-e9af043e-46fd-11e8-8533-047d915f2e2b.png)

It only sees a minimal menu with itself on it.

OS is Ubuntu 18.04.

App was installed from the Ubuntu Software app, but on flatpak.

**Comment by TingPing** [comment]
My comment already said how to fix it: https://github.com/flathub/flathub/pull/266#issuecomment-366515553

Honestly it probably should have been fixed before getting added to the repo.

**Comment by bilelmoussaoui** [comment]
@TingPing Would love to get some help on this! Tried every solution I have in mind but couldn't get things to work correctly...

**Comment by TingPing** [comment]
Well here is a minimal reproducer for GLib:

```
flatpak run --filesystem=host --env=XDG_DATA_DIRS=/usr/share --command=python3 org.gnome.Sdk//3.28 -c 'from gi.repository import Gio; print(list(a.get_name() for a in Gio.AppInfo.get_all()))'
```

Glancing at the code in Gio I do not see any obvious bugs so it would take some deeper debugging: https://github.com/GNOME/glib/blob/master/gio/gdesktopappinfo.c

**Comment by stuaxo** [comment]
Maybe try installing FlatSeal and using it to poke at the permissions.
I had some luck finding which permission was at fault in another flatpak app that way, but don't have time to look @ appeditor right now.

**Comment by ryukinix** [comment]
Honestely appeditor running through flatpak is useless for me. I can't even create a new launcher from another program, because it verifies if the command exists and inside of it and don't allow to save it (frustrating).

Even running appeditor through distrobox in a arch-linux based container can be more useful, through will have similar problems. The best option is install natively, arch-linux is easy from aur, but for ubuntu/debian you need to build the package by yourseulf since is not distributed the .deb packages at each release (I understand the focus being elementaryOS).
